defaults: &defaults
  fog_provider: 'AWS'
  aws_access_key_id: "<%= Rails.application.credentials.dig(:docean, :mlospaceks) %>"
  aws_secret_access_key: "<%= Rails.application.credentials.dig(:docean, :secret) %>"

  # To use AWS reduced redundancy storage.
  # aws_reduced_redundancy: true
  #
  # Change AWS signature version. Default is 4
  # aws_signature_version: 4
  #
  # Change canned ACL of uploaded object. Default is unset. Will override fog_public if set.
  # Choose from: private | public-read | public-read-write | aws-exec-read |
  #              authenticated-read | bucket-owner-read | bucket-owner-full-control
  aws_acl: public-read
  #
  # Change host option in fog (only if you need to)
  fog_host: "sfo3.digitaloceanspaces.com"
  #
  # Change port option in fog (only if you need to)
  # config.fog_port = "9000"
  #
  # Use http instead of https. Default should be "https" (at least for fog-aws)
  # fog_scheme: "http"
  fog_directory: "cdn-mlo"

  # You may need to specify what region your storage bucket is in
  fog_region: "sfo3"

  # Set `public` option when uploading file depending on value,
  # Setting to "default" makes asset sync skip setting the option
  # Possible values: true, false, "default" (default: true)
  #config.fog_public = true

  #existing_remote_files: keep
  # To delete existing remote files.
  existing_remote_files: delete

  # Automatically replace files with their equivalent gzip compressed version
  gzip_compression: true

    # Fail silently.  Useful for environments such as Heroku
  # fail_silently: true

  # Allow custom assets to be cacheable. Note: The base filename will be matched
  # cache_asset_regexps: ['cache_me.js', !ruby/regexp '/cache_some\.\d{8}\.css/']

development:
  <<: *defaults
  enabled: false

test:
  <<: *defaults
  enabled: false

staging:
  <<: *defaults
  fog_directory: "mlo-staging-assets"

production:
  <<: *defaults
