default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= Rails.application.credentials.dig(:postgres, :username) %>
  password: <%= Rails.application.credentials.dig(:postgres, :password) %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: mlo_development

test:
  <<: *default
  database: mlo_test

production:
  <<: *default
  username: <%= Rails.application.credentials.dig(:postgres, :prod_username) %>
  password: <%= Rails.application.credentials.dig(:postgres, :prod_password) %>
  database: mlo_production
