test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
digitalocean:
  service: S3
  endpoint: 'https://cdn.masterleagueonline.com.br'
  access_key_id: <%= Rails.application.credentials.dig(:docean, :mlospaceks) %>
  secret_access_key: <%= Rails.application.credentials.dig(:docean, :secret) %>
  bucket: cdn-mlo